config/routes.rb
Ecspy::Application.routes.draw do
  

  get "ztc/check",:as => :ztc_check
  get "ztc/status",:as => :ztc_status
  get "ztc/proxy",:as => :ztc_proxy
  post 'ztc/clear',:as => :ztc_clear
  post "ztc/save",:as => :ztc_save

  get "file_upload/index"

  post "file_upload/upload"

  match "user_center/index" => 'user_center#index' ,:as => :user_root

  root to: 'user_center#index'

  devise_for :users,:controllers => { :registrations => "registrations" }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match 'shop_items/:id/content/:fversion/:sversion' => 'shop_items#content_compare', :as => :content_compare

  resources :shop_items do
    member do
    end
  end

  namespace :user_center do 
    resources :shops do

      collection do

        post 'subscribe'

        post 'unsubscribe'

        get 'compare'
      end

    end

    resources :items

    resources :sales

    resources :keywords

    resources :keyword_records do
      member do 
        get 'trend'
      end
    end

  end 

end

app/controllers/user_center/items_controller.rb
class UserCenter::ItemsController < ApplicationController
	before_filter :authenticate_user!
	layout 'smart_admin'

	def index
		shop_id = params['shop_id'].to_i
		@shop = Shop.find(shop_id)
		where = "shop_id = #{shop_id}" if shop_id > 0
		@tasks_grid = initialize_grid(ShopItem,
		:include => [:shop],
		:conditions => where,
	     :custom_order => {
	    })
	end

end

app/controllers/user_center/keyword_records_controller.rb
class UserCenter::KeywordRecordsController < ApplicationController

	before_filter :authenticate_user!
 	layout 'smart_admin'


	def index

		# @records = []
		# ShopKeywordRecord.includes(:shop,:shop_item,:shop_keyword).select('t3.user_id').where("user_id =  #{current_user.id}").each do |r|
		# 	@records << {
		# 		'title' => r.shop.title,
		# 		'shop_id'=>r.shop_id,
		# 		'item_title' => r.shop_item.title,
		# 		'item_id' => r.item_id,
		# 		'rank' => r.rank,
		# 		'keyword' => r.shop_keyword.keyword
		# 	}

		# end	

		last_time = Time.now.beginning_of_day
		if ShopKeywordRecord.where(['created_at > ?',last_time]).size == 0
			last_time = last_time - 1.day
		end
		@records = initialize_grid(                                                                #where("user_id = 1 ")
		  ShopKeywordRecord.includes(:shop,:shop_item,:shop_keyword).select('shop_keywords.user_id').where("user_id = #{current_user.id}").where(['

		  	shop_keyword_records.created_at >=?',last_time]),

	     :custom_order => {
	    })
	end

		

	def trend
		record = ShopKeywordRecord.find(params[:id])


		start_time = Time.now.end_of_day-30.days
		end_time = Time.now.end_of_day


		records = ShopKeywordRecord.select(' date_format(created_at,"%y-%m-%d") as time,avg(rank) as rank').where(
			['shop_id = ? and item_id = ? and shop_keyword_id = ? and created_at between ? and ?',record.shop_id,record.item_id,record.shop_keyword_id,start_time,end_time]).group('time').order('time asc')



		res = []
		start_time_stamp = start_time.beginning_of_day.to_i
		end_time_stamp = end_time.beginning_of_day.to_i
		current_time_stamp = start_time_stamp
		one_day_sec = 1.day
		
		index = 0
		31.times do |i|
			if Time.at(current_time_stamp).strftime('%y-%m-%d') == records[index].time
				res << records[index].rank
				index += 1
				index = 0 if index >= records.size
			else
				res << 0
			end

			current_time_stamp += one_day_sec
		end
		res

		respond_to do |format|
		  format.json { render :json => res }
		end

	end
end

app/controllers/user_center/keywords_controller.rb
#encoding:utf-8
class UserCenter::KeywordsController < ApplicationController
	before_filter :authenticate_user!
	layout 'smart_admin'

	def index
		@shops_map ={}
	 	Shop.watched(current_user.id).each do |r|
	 		@shops_map[r.id] = r.title
		end
		@keywords = current_user.keywords
	end


	def new
	  	@keyword = ShopKeyword.new
	  	# respond_to do |format|
	   #    format.html { render :layout => false }
	   #  end

	end



	def create

	 	data = params[:shop_keyword]
	 	data["shops"] = data["shops"].join(",").chomp(',')
	 	data["user_id"] = current_user.id

	 	@keyword = ShopKeyword.new(data)
		if @keyword.save
			flash[:notice] = '关键字创建成功.'
			redirect_to :action => :index
		else

			render :action => :new
		end
	end


	def destroy
		  @keyword = ShopKeyword.find(params[:id])
		  @keyword.destroy
		  flash[:notice] = '删除成功.'
		  redirect_to :action => :index

	end
end

app/controllers/user_center/shops_controller.rb
#encoding:utf-8
class UserCenter::ShopsController < InheritedResources::Base
  include StaticsHelper
  include UserCenterHelper

  
  before_filter :authenticate_user!

  layout 'smart_admin'

  def index


  end


  def new
  	@shop = Shop.new
  end



  def create
    create! do |success, failure|
      
      success.html { 
        current_user.follow(@shop)
        redirect_to user_center_shops_path,:notice=>'创建成功'
      }
    end
  end



  def subscribe

  		shop_id = params['shop_id'].to_i

  		#@TODO replace with current_user
  		current_user.follow( Shop.find(shop_id)) 

  		render text: shop_id.to_s
  end


  def unsubscribe

  		shop_id = params['shop_id'].to_i

  		#@TODO replace with current_user

  		current_user.stop_following( Shop.find(shop_id)) 

  		render text: shop_id.to_s


  end



  def compare

    @offset = params['offset'].to_i
    @offset ||= 0
    shops = params['id'].split(',')
    shops.collect! &:to_i



    @res = []

    shops.each do |s|
      shop = Shop.find(s)
      row = {'title' => shop.title,'id'=>shop.id}
      row['sales'] = get_sales_history(shop.id,@offset)

      
      @res << row
    end

  end


  def show
    #time = Time.now.beginning_of_day
    offset = params['offset'].to_i

    offset ||= 0
    @shop = Shop.find(params['id'])

    @today = calc_sales_count_and_money(@shop.today_sales(offset))

    yesterday = calc_sales_count_and_money(@shop.today_sales(offset + 1 ))

    lastweekday = calc_sales_count_and_money(@shop.today_sales(offset + 7 ))



    today_changes_sales = today_changes(@shop.id,offset)

    @yes_compare = get_compare_rate(@today,yesterday)

    @lastweekday_compare = get_compare_rate(@today,lastweekday)

    sales_history = get_sales_money_history(@shop.id,offset)
    count_history = get_sales_count_history(@shop.id,offset)

    sales_total = sales_history.inject(0) {|sum,i| sum + i} 
    count_total= count_history.inject(0) {|sum,i| sum + i} 


    @locals = { :today => @today,:lastweekday_compare => @lastweekday_compare, :sales_history=>sales_history,:count_history => count_history,
    :yes_compare => @yes_compare ,:shop => @shop ,:offset=>offset,:today_changes_sales => today_changes_sales,
    :sales_total =>sales_total,:count_total=>count_total

    }

    #hack ugly?
    respond_to do |format|
      format.html
      format.js {
         render :partial => 'show_data',:locals => @locals,:layout=>false ,:mime_type => Mime::Type.lookup('text/html')
      }
    end

    #5 top items
  end





end

app/controllers/user_center/test_controller.rb
class UserCenter::TestController < ApplicationController
  def index
  end
end

app/controllers/user_center_controller.rb
class UserCenterController < ApplicationController
	
  helper StaticsHelper
  before_filter :authenticate_user!
  layout 'smart_admin'


  def index
  	@offset = params['offset'].to_i
  	@shops = current_user.following_by_type('Shop')

  end


end

app/helpers/user_center/items_helper.rb
module UserCenter::ItemsHelper
end

app/helpers/user_center/keyword_records_helper.rb
module UserCenter::KeywordRecordsHelper
end

app/helpers/user_center/keywords_helper.rb
module UserCenter::KeywordsHelper

	def shopids_to_titles(ids,maps)
		ids = ids.split(',')

		res = ''
		ids.each do |id|
			id = id.to_i
			res = res + maps[id] + '&nbsp;' if maps[id]
		end
		res
	end



end

app/helpers/user_center_helper.rb
#encoding:utf-8
module UserCenterHelper

	def link_with_cur(path,title)
		cur = 'cur' if request.path == path
		"<li><a href='#{path}' class='#{cur}'><i class='icon-chevron-right'></i> #{title} </a></li>"
	end



	def today_change_count(shop,offset =0)

			 ShopItemVersion.today_changes(shop,offset).size +  
			 ShopItemContentVersion.today_changes(shop,offset).size
	end
	

	def my_img_tag(thumb,css_class)
		"<img  class='#{css_class}' src='#{thumb}'>"
	end

	def today_changes(shop,offset=0)


		res = []

  		today_changes = ShopItemVersion.today_changes(shop,offset)
		
		today_changes_cache = {}
  		today_changes.each do |r|
  			today_changes_cache["#{r.shop_item_id}_#{r.version}"] = r
  		end

		today_changes.each do |r|
			item = today_changes_cache["#{r.shop_item_id}_#{r.version}"]

			if item.version != 1
				last = item
				prev = today_changes_cache["#{r.shop_item_id}_#{r.version-1}"]

				if prev.nil?
					prev = ShopItemVersion.includes(:shop_item).where(:shop_item_id => r.shop_item_id,:version=>r.version-1).limit(1).first
				end


				change = "［商品］：<a href='/shop_items/#{item.shop_item.id}' >#{last.title}</a> "

				change += " 价格变化 #{prev.price} => #{last.price}" if last.price != prev.price

				change += " 标题变化 #{prev.title} => #{last.title}" if last.title != prev.title
				
				change += " 状态变化 #{ShopItem.status_text prev.status} => #{ShopItem.status_text last.status}" if last.status != prev.status

				change += " 主图变化 #{my_img_tag prev.thumb,'small'} => #{my_img_tag last.thumb,'small'}" if last.thumb != prev.thumb

			else
				change = "［新品］:<a href='/shop_items/#{item.shop_item.id}' >#{item.title}</a> 新上架"

			end

			res << change

		end 




	 	ShopItemContentVersion.today_changes(shop,offset).each do |r|
	 		item = ShopItemContent.find(r.shop_item_content_id)
	 		if item.versions.count != 1
		 		last = item.versions.last
				prev = last.previous


		 		change = "［内容］:<a href='/shop_items/#{item.shop_item.id}' >#{item.shop_item.title}</a> 内容变化 "

				change +=  " <a href='/shop_items/#{item.shop_item.id}/content/#{last.version}/#{prev.version}' > 对比 </a>"

				#{content_compare_path(:id=>item.shop_item.id,:fversion=>last.version,:sversion=>prev.version)}

			else
				change = "［内容］:<a href='/shop_items/#{item.shop_item.id}' >#{item.shop_item.title}</a> 内容创建"

			end

			res << change

	 	end


	 	res

	end


	def today_sales(shop,offset=0)
		res = {}
		sales = shop.today_sales(offset)
		sales.each do |s|
			if !res[s.shop_item.id]
				row = {}
				row['item'] = link_to s.shop_item.title, "/shop_items/#{s.shop_item.id}"
				row['img'] = link_to image_tag(s.shop_item.thumb),"/shop_items/#{s.shop_item.id}"
				row['count'] = s.item_num.to_i
				row['money'] = s.item_num.to_i * s.item_price.to_f
				res[s.shop_item.id] = row
			else
				res[s.shop_item.id]['count'] += s.item_num.to_i
				res[s.shop_item.id]['money'] += s.item_num.to_i* s.item_price.to_f
			end
		end
		res = res.to_a.sort do |a,b|
			b[1]['money'] <=>  a[1]['money']
		end
		res
	end


	def get_preview(id,time)
		"/preview/#{id}/#{time.strftime('%Y-%m-%d')}.jpg"
	end

	def get_preview_small(id,time)
		"/preview/#{id}/#{time.strftime('%Y-%m-%d')}-small.jpg"
	end


	def get_change_icon(status)
		if status == 1
			'<img src="/assets/zeng.gif">'.html_safe
		else
			'<img src="/assets/jian.gif">'.html_safe
		end

	end

	def get_sales_history(id,offset,search_way = :by_shop)
		start_time = Time.now.end_of_day-30*24*3600 -offset*24*3600 
		end_time = Time.now.end_of_day-offset*24*3600
		#ShopItem.includes(:shop_item).
		#ItemSale.joins(:shop_item).select('date_format(buy_time,"%y-%m-%d") as time ,sum(item_price * item_num) as total').where(['shop_id = 1 and buy_time between ? and ?',Time.now-3*24*3600 , Time.now]).group('time')
		
		conditions = nil
		if search_way === :by_shop
			conditions = ['shop_id = ? and buy_time between ? and ?',id,start_time,end_time]
		else #by_item
			conditions = ['shop_items.id = ? and buy_time between ? and ?',id,start_time,end_time]
		end


		sales = ItemSale.joins(:shop_item).select(' date_format(buy_time,"%y-%m-%d") as time,count(DISTINCT buy_time,user_name) as item_count, sum(item_price * item_num) as total').where(conditions).group('time').order('time asc')
		

		res = []
		start_time_stamp = start_time.beginning_of_day.to_i
		end_time_stamp = end_time.beginning_of_day.to_i
		current_time_stamp = start_time_stamp
		one_day_sec = 3600*24
		sales_index = 0

		if sales[0]
			31.times do |i|
				if Time.at(current_time_stamp).strftime('%y-%m-%d') == sales[sales_index].time
					res << [ sales[sales_index].item_count.to_i,sales[sales_index].total.round(2)]
					sales_index += 1
					sales_index = 0 if sales_index >= sales.size
				else
					res << [0,0]
				end

				current_time_stamp += one_day_sec
			end
		else
			31.times do |i|
				res << [0,0]
			end
		end
		res
	end


	def get_sales_money_history(id,offset,search_way = :by_shop)
		res = get_sales_history(id,offset,search_way)
		res.collect &:second
	end


	def get_sales_count_history(id,offset,search_way = :by_shop)
		res = get_sales_history(id,offset,search_way)
		res.collect &:first
	end
	#sales_history = get_sales_histroy(@shop,offset)

end

app/views/user_center/_menu.html.erb
<ul class="nav nav-list bs-docs-sidenav affix-top">

<%= link_with_cur(user_root_path,'今日').html_safe%>
<%= link_with_cur(user_center_shops_path,'店铺').html_safe%>
<%= link_with_cur(user_center_keywords_path,'搜索设置').html_safe%>
<%= link_with_cur(user_center_keyword_records_path,'搜索排名').html_safe%>


  <li><a href="<%=user_center_items_path%>"><i class="icon-chevron-right"></i> 产品 </a></li>
  <li><a href="#contents"><i class="icon-chevron-right"></i> 我的消息 </a></li>
</ul>

app/views/user_center/_time_select.html.erb
<div class="search col-xs-12 col-sm-12 col-md-12"><form action="index.php" method="get"><input type="hidden" name="m" value="stats">
<input type="hidden" name="c" value="order">
<input type="hidden" name="a" value="order_overview">
<a href="" time="today" class="col-xs-4 col-sm-1 col-md-1">今天</a><a href="" time="yesterday" class="col-xs-4 col-sm-1 col-md-1" >昨天</a><a href="" time="yyday" class="col-xs-4 col-sm-1 col-md-1" >前天</a>
<%= content_for :script do %>
<script type="text/javascript">


$(function()
{
	var timeRange = {

		'today': {
			'offset':0,
		},
		'yesterday': {
			'offset':1,
		},
		'yyday': {
			'offset':2,
		},
	}
	function directToUrl(start)
	{
		var href = window.location.href;
		if(href.indexOf('offset')!=-1)
			href = href.substr(0,href.indexOf('offset')-1)

		if(href.indexOf('&') != -1)
			href = href + '&'
		href = href + '?offset=' +start ;

		window.location.href = href;
	}
	$('.search a').click(function(){

		var time = timeRange[$(this).attr('time')];

		var start = time.offset;
		
		directToUrl(start);
	
		return false;
	});

});
</script> 
<% end %>
<!-- <input type="button" id="searchBtn" class="button" value="搜索" title="提示：由于系统限制，您目前只能查询最近三个月数据"> -->
<style type="text/css">
.table-list td,.table-list th{padding:3px;padding-left:3px;}
.table-list tbody td,.table-list .btn{border-bottom: #ddd 1px solid; padding-top:5px; padding-bottom:5px}
.table-list thead th{height:30px; background:#eef2f2; border-bottom:1px solid #d5dfe8; font-weight:normal}
.td-line{border:1px solid #ddd;border-top:0;}
.td-line td{border:1px solid #ddd;border-top:0;}
</style>
</form></div>

app/views/user_center/index.html.erb
<div class="row">
<%= render :partial => "/user_center/time_select" %>  


<dl class="dl-horizontal col-xs-12 col-sm-12 col-md-12">

	<dt class="col-xs-6"> last items: </dt>

	<dd class="col-xs-6">   <%= Shop.order('updated_at desc').limit(1).first.updated_at %>             </dd>


	<dt class="col-xs-6"> last sales: </dt>

	<dd class="col-xs-6">   <%= ShopItem.order('last_check_time desc').limit(1).first.last_check_time %>             </dd>
</dl>
<% @shops.each do |shop| %>

<section>
	<div class="col-xs-12 col-sm-4 col-md-4 text-center panel panel-default">
		<div class="panel-body">
			<h3> <%= link_to shop.title,user_center_shop_path(shop) %>  </h3>


			<dl class="dl-horizontal"> 
				<dt>当日订单：</dt>

				<% today_sales = calc_sales_count_and_money(shop.today_sales(@offset)) %>
				<dd> <strong class="text-danger">  <%= today_sales[0] %> </strong> 个 </dd>

				<dt>当日金额： </dt>
				<dd> <strong class="text-danger"> <%= today_sales[1] %>  </strong> 元 </dd>


			</dl>
			<div> <small> <a class='compare_btn'  style="cursor:pointer" data-id="<%=shop.id%>" data-title="<%=shop.title%>" > <i class="icon-plus"></i> 加入对比 </a>  </small></div>
			<div class="accordion" id="accordion<%=shop.id%>">
				<div class="accordion-group">



			    	<div class="accordion-heading">
			      		<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion<%=shop.id%>" href="#collapse<%=shop.id%>">
			      			<% today_changes_sales = today_changes(shop,@offset) %>
			       	 		当日行为（<%= today_changes_sales.count %>）
			      		</a>
			    	</div>
			    	<div id="collapse<%=shop.id%>" class="accordion-body collapse ">
			      		<div class="accordion-inner">
							<ul> 
								<% today_changes_sales.each do |change| %>

									<li>
										<%= change.html_safe %>
									</li>


								<% end %>
							
							</ul>

			      		</div>
			    	</div>
			   </div>
		   </div>


			<div class="accordion" id="accordion_sale<%=shop.id%>">
				<div class="accordion-group">



			    	<div class="accordion-heading">
			      		<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion_sale<%=shop.id%>" href="#collapse_sale<%=shop.id%>">
			       	 		具体销售
			      		</a>
			    	</div>
			    	<div id="collapse_sale<%=shop.id%>" class="accordion-body collapse ">
			      		<div class="accordion-inner">
							<ul> 
								<% today_sales(shop,@offset).each do |k,sale| %>
									<li>
										<%= sale['item'] %> &nbsp;&nbsp; 数量：<%= sale['count'] %>&nbsp;&nbsp; 总金额: <%= sale['money'].round(2) %>
									</li>




								<% end %>
							
							</ul>

			      		</div>
			    	</div>
			   </div>
		   </div>
		</div>
	</div>

</section>
	

<% end %>


<div class="compare_list span2 text-center" style="display:none" >
	<h4> 店铺对比  </h4>
	<ul id="compare_list" class="text-left"> 
	</ul>
	<hr>
	<div>

		<button class="btn-primary" id="do_compare" > 开始对比 </button>
		
		<small> <a class="clear" href="javascript:void(0)"> 清空 </a> </small>
	</div>

	<p class="text-center">  <a href="javascript:void(0)" class="collapse_btn"> <i class="fa fa-angle-double-up"> </i> </a> </p>
</div>


</div>
<%= content_for :script do %>
<script type="text/javascript">
	
	$(function(){

		$('.compare_btn').click(function(){
			compare_list.ele.show();
			compare_list.append(this);
		});

		$(document).on("click","#compare_list li i",function(){ compare_list.remove(  $(this).closest('li')) });





		var compare_list = {
			ele : $('.compare_list'),
			cell: $('#compare_list'),
			clearBtn : $('.compare_list .clear'),
			collapseBtn: $('.compare_list .collapse_btn'),
			keys_hash : {},
			bindCancel:function(ele){
				ele.click(function(){
					
				})
			},
			ids:function()
			{	
				var ids = [];
				for(var i in this.keys_hash)
				{
					ids.push(i);
				}

				ids.join(',');
				return ids;
			},
			append:function(shop)
			{

				var id = $(shop).attr('data-id');
				var title =  $(shop).attr('data-title');
				if(this.keys_hash[id] == undefined)
				{
					if(this.cell.find('li').size() <4)
					{

						var html = '<li data-id="' +  id + '"><small> '  + title + '</small> <i class="icon-remove "> </i> </li>';
						//this.bindCancel($(html).find('i'));

						this.cell.append( html);

						this.keys_hash[id] = title;
					}
					else{
						alert('最大支持4个商店')
					}
				}
			},
			remove:function(ele)
			{

				id = ele.attr('data-id');
				this.keys_hash[id] = undefined;
				ele.remove();
			},

			init:function()
			{
				this.clearBtn.click($.proxy(function(){

					this.keys_hash = {};
					this.cell.html('');

				}, this));

				this.collapseBtn.click($.proxy(function(){

					this.ele.hide();

				}, this));
			}

		}

		compare_list.init();


		$('#do_compare').click(function(){

			var url = "<%=compare_user_center_shops_path%>";

			url = url +'?id=' + compare_list.ids();

			window.location.href=url;

		});
	});


</script>
<% end %>

app/views/user_center/shops.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="span3">
			
			<%= render :partial => "menu" %>  
		</div>


		<div class="span9">
			
			Shops
		</div>



	</div>
</div>