config/routes.rb
Ecspy::Application.routes.draw do
  

  get "ztc/check",:as => :ztc_check
  get "ztc/status",:as => :ztc_status
  get "ztc/proxy",:as => :ztc_proxy
  post 'ztc/clear',:as => :ztc_clear
  post "ztc/save",:as => :ztc_save

  get "file_upload/index"

  post "file_upload/upload"

  match "user_center/index" => 'user_center#index' ,:as => :user_root

  root to: 'user_center#index'

  devise_for :users,:controllers => { :registrations => "registrations" }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match 'shop_items/:id/content/:fversion/:sversion' => 'shop_items#content_compare', :as => :content_compare

  resources :shop_items do
    member do
    end
  end

  namespace :user_center do 
    resources :shops do

      collection do

        post 'subscribe'

        post 'unsubscribe'

        get 'compare'
      end

    end

    resources :items

    resources :sales

    resources :keywords

    resources :keyword_records do
      member do 
        get 'trend'
      end
    end

  end 

end

app/controllers/ztc_controller.rb
#encoding:utf-8
require 'tasks/crawler'
class ZtcController < ApplicationController
  before_filter :authenticate_user!
  layout 'smart_admin'

  
  def check
  	 respond_to do |format|
      format.html
      format.json {
      	 retn = Crawler::ZTC.get_ztc_list(params[:keyword],params[:proxy])
         render  :text => retn
      }
    end
  end


   def proxy
     respond_to do |format|
      format.html
      format.json {
         retn = Proxy.get_proxy
         res = {'code'=>1}
         if retn #ok
            res['code'] = 0
            res['proxy'] = retn
         end 
         render  :json => res
      }
    end
  end


  def save 

      arr = {
        'keyword' => params['keyword'],
        'count' => params['count'].to_i,
      }
      arr['proxy'] = params['proxy'] if params['proxy'] =~ /\d+/


      items = params["items"]

      items.each do |item|
          puts item
          arr['item_id'] = item.chomp
          Crawler::ZTC.generate_jobs(arr)
      end

      flash[:notice] = '任务创建成功'
      redirect_to :action => :status

  end


  def status
    jobs_list = Crawler::ZTC.get_job_list
    @jobs_list = []
    jobs_list.each do  |job|
      job = JSON.parse(job)
      @jobs_list << job.merge('done' =>  Crawler::ZTC.get_job_done_count(job['id']))
    end

  end

  def clear
      Crawler::ZTC.clear_all
      flash[:notice] = '任务清理成功'
      redirect_to :action => :status
  end

end

app/helpers/ztc_helper.rb
module ZtcHelper
end

app/views/ztc/check.html.erb
<style type="text/css">
	.ztc_img{
		width: 50px;
		height: 50px;
	}

</style>
<section id="widget-grid" class="">
	
	<!-- row -->
	<div class="row">
	
		<!-- NEW WIDGET START -->
		<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	

			
		<div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false">
			
			<header>
				<span class="widget-icon"> <i class="fa fa-eye"></i> </span>
				<h2>直通车查询</h2>

			</header>

			<!-- widget div-->
			<div>
				<%= form_tag(ztc_save_path, method: "post") do %>
					<!-- widget edit box -->
					<div class="jarviswidget-editbox">
						<!-- This area used as dropdown edit box -->

					</div>
					<!-- end widget edit box -->

					<!-- widget content -->
					<div class="widget-body">


						<h3> 1、参数配置 </h3>
						
	 					<%= label_tag(:proxy, "代理地址：") %>
	 					<%= text_field_tag(:proxy) %>	
						<%= button_tag("获取",:id=>'proxy_btn',:type => 'button') %><br>
	

						<%= label_tag(:count, "点击次数：") %>
	 					<%= text_field_tag(:count,200) %>	



						<h3> 2、选择对象 </h3>
						<%= label_tag(:keyword, "输入关键字：") %>
	 					<%= text_field_tag(:keyword) %>	
					

						<%= button_tag("搜索",:id=>'search_btn',:type => 'button') %>
						<%= button_tag("清空",:id=>'clear_btn',:type => 'button') %>

						<div class='result row' >
							
						</div>
		
					
						<hr>
						<%= submit_tag("开刷！") %>
					</div>
				<%end %>
			</div>
		</div>


		</article>
</div>
</section>
<script id="key-results-tmp" type="text/html">
<ul>
    <! for(i = 0; i < list.length; i ++) {  !>
        <li class="col-xs-12 col-sm-12 col-md-6 col-lg-6"> 
        	 <input name="items[]" type="checkbox" value="<!=list[i].id!> ">

        	 <a target="_blank"  href="<!=list[i].link!>"> <!= list[i].title !> </a>  <a target="_blank" href="<!=list[i].img!>" ><img class="ztc_img" src="<!=list[i].img!>" /> </a>

        </li>
    <! } !>
</ul>
</script>


<%= content_for :script do %>
<script type="text/javascript">
	
	$(function(){

		template.openTag = "<!";
		template.closeTag = "!>";


		
        var spinner = new Spinner();
		//select all
		$('#search_btn').click(function(){
			if($('#keyword').val() != '')
			{
				$('#search_btn').attr('disabled',true);

				var data = {'keyword':$('#keyword').val()};
				if($('#proxy').val())
					data['proxy'] = $('#proxy').val();
				$.ajax({
					'type':'get',
					'url':'<%=ztc_check_path :format => "json"%>',
					'dataType':'json',
					'data':data,
					beforeSend: function () {
	                    //异步请求时spinner出现
	                     var target = $(".widget-body").get(0);
	                    spinner.spin(target);                    
	                },
					'success':function(data){
						var reswrapper = $('.result')
							spinner.spin();
						$('#search_btn').attr('disabled',false);

						if(data.length == 0)
						{	
							alert('获取失败，请重新尝试');
						}
						else {

							var html = template.render('key-results-tmp', {list:data})
							reswrapper.append(html);
						}
											

					}


				})
			}

		});


		//proxybtn
		$('#proxy_btn').click(function(){
			$('#proxy_btn').attr('disabled',true);
			$.ajax({
				'type':'get',
				'url':'<%=ztc_proxy_path :format => "json"%>',
				'dataType':'json',
				beforeSend: function () {
                    //异步请求时spinner出现
                     var target = $(".widget-body").get(0);
                    spinner.spin(target);                    
                },
				'success':function(data){
					if(data.code == 0)
					{
						$('#proxy').val(data.proxy);
					}
					else
					{
						alert('获取失败，请重新尝试');
					}
					spinner.spin();
					$('#proxy_btn').attr('disabled',false);
				}


			})

		});
		
		//clear
		$('#clear_btn').click(function(){
			$('.result').html('');
		})
		//validate form
		$('form').submit(function() {
			var error = '';

			if($("input[name='items[]']:checked").length == 0)
				error += '至少应选择一个产品';


			if(error!='')
			{
				alert(error);
				return false;
			}

	        return true; // return false to cancel form action
	    });
	})

</script>
<% end %>

app/views/ztc/status.html.erb
<section id="widget-grid" class="">
	
	<!-- row -->
	<div class="row">
	
		<!-- NEW WIDGET START -->
		<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	

			<% if flash[:notice] %>
				<div class="alert alert-notice">
					<strong><%= flash[:notice] %></strong>
				</div>
			<% end %>


			


			

			<div class="jarviswidget jarviswidget-color-darken" id="wid-id-1" data-widget-editbutton="false">
				<header>
					<span class="widget-icon"> <i class="fa fa-table"></i> </span>
					<h2> 任务队列 
						
					</h2>
				</header>
				<div>
				
					<!-- widget edit box -->
					<div class="jarviswidget-editbox">
						<!-- This area used as dropdown edit box -->

					</div>
					<!-- end widget edit box -->

					<!-- widget content -->
					<div class="widget-body no-padding">
									
						<div class="widget-body-toolbar">
								<div class="text-right">
									<%= link_to ztc_clear_path ,class:'btn btn-primary',method:'post' do%>
										<i class="fa fa-plus"></i>清空
									<% end %> 
						 		</div> 
							</div>	
						<table class="table" id="shop_keyword_tabel" class="table table-striped table-bordered smart-form">
							<thead>
								<tr> 
									<Th> 任务id</th>

									<th> 关键字 </th>

									<th> 产品id </th>

									<th> 点击次数 </th>

									<th> 完成次数 </th>

									<th> 开始时间 </th>
								</tr>
							</thred>

							<tbody>
								<% @jobs_list.each do |job| %>
									<tr>	
										<td><%= job['id']%></td>
										<td><%= job['keyword']%></td>
										<td><%= job['item_id']%></td>
										<td><%= job['count']%></td>
										<td><%= job['done']%></td>
										<td><%= job['time']%></td>

									</tr>
								       
								<% end %>

							</tbody>

						</table>
					</div>
										<!-- end widget content -->
					
				</div>
					<!-- end widget div -->

			</div>
			<!-- end widget -->


		</article>

	</div>

</section>


<ul>
	
	

</ul>
<script src="http://js.pusher.com/2.1/pusher.min.js" type="text/javascript"></script>
<%= content_for :script do %>
<script type="text/javascript">
	  Pusher.log = function(message) {
      if (window.console && window.console.log) {
        window.console.log(message);
      }
    };

    var pusher = new Pusher('dead170cf3df76678bc5');
    var channel = pusher.subscribe('test_channel');
    channel.bind('my_event', function(data) {
      alert(data.message);
    });
</script>
<% end %>