config/routes.rb
Ecspy::Application.routes.draw do
  

  get "ztc/check",:as => :ztc_check
  get "ztc/status",:as => :ztc_status
  get "ztc/proxy",:as => :ztc_proxy
  post 'ztc/clear',:as => :ztc_clear
  post "ztc/save",:as => :ztc_save

  get "file_upload/index"

  post "file_upload/upload"

  match "user_center/index" => 'user_center#index' ,:as => :user_root

  root to: 'user_center#index'

  devise_for :users,:controllers => { :registrations => "registrations" }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match 'shop_items/:id/content/:fversion/:sversion' => 'shop_items#content_compare', :as => :content_compare

  resources :shop_items do
    member do
    end
  end

  namespace :user_center do 
    resources :shops do

      collection do

        post 'subscribe'

        post 'unsubscribe'

        get 'compare'
      end

    end

    resources :items

    resources :sales

    resources :keywords

    resources :keyword_records do
      member do 
        get 'trend'
      end
    end

  end 

end

app/models/shop.rb
#encoding:utf-8
class Shop < ActiveRecord::Base
	attr_accessible :title,:url,:goods_num, :disabled

	validates_presence_of :url,:title
	validates_uniqueness_of :url

	acts_as_followable

	has_many :shop_items ,:dependent => :destroy

	has_many :shop_contents, :through => :shop_items,:source => :content

	#not update in 6 hours or created in 6 hours
	scope :recently_not_updated,where( ["updated_at < ? or ( created_at > ?  and updated_at = created_at )", Time.now - 3.hour, Time.now - 3.hour])

	#scope :unwatched, lamda {|user|  self.ALl - User.find(user).followed  }

	default_scope where(:disabled => 0)

	def touch
		if !new_record?
			update_attribute(:updated_at,Time.new);
		end
	end



	def tmall?
		self.url.index("tmall")
	end


	def today_sales(offset = 0)
		ItemSale.includes(:shop_item,:shop).where(['shops.id= ? and (buy_time > ? and buy_time < ? )',self.id, Time.new.beginning_of_day-offset*3600*24,Time.now.end_of_day-offset*3600*24])
	end


	# def today_sales(offset = 0)
	# 	sum = []
	# 	shop_items.each {|item|
	# 		#puts " #{item.id} #{item.title} #{item.today_sales_money} #{item.today_sales_money}"
	# 		res = item.today_sales(offset)
	# 		sum.concat res if res.count > 0
	# 	}
	# 	sum
	# end


	def today_sales_count(offset = 0)
		shop_items.inject(0) {|sum,item|
			#puts " #{item.id} #{item.title} #{item.today_sales_count}"

			sum + item.today_sales_count(offset)
		}
	end

	def today_sales_money(offset = 0)
		shop_items.inject(0) {|sum,item|
			#puts " #{item.id} #{item.title} #{item.today_sales_money} #{item.today_sales_money}"
			sum + item.today_sales_money(offset)
		}
	end


	def self.unwatched(user)
		watched = User.find(user).following_by_type(self.name)

		watched_ids = []
		watched.each do |w|
			watched_ids << w
		end
		#in case of watche_ids is null
		watched_ids << -1
		where(['id not in (?)', watched_ids ])

	end


	def self.watched(user)
		watched = User.find(user).following_by_type(self.name)
	end


	validate :url_validate
	def url_validate
	    #unless url  =~ /^http:\/\/(\w)*.(tmall|taobao).com\/$/
	    unless url  =~ /^http:\/\/(\w)*.(tmall).com\/$/
	    	errors[:url] << 'url格式不正确 参考 ： http://slwsp.tmall.com/'
	    end
  	end

#
	# before save do
	# 	url << '/' if url.last != '/'
	# end


end

app/controllers/user_center/items_controller.rb
class UserCenter::ItemsController < ApplicationController
	before_filter :authenticate_user!
	layout 'smart_admin'

	def index
		shop_id = params['shop_id'].to_i
		@shop = Shop.find(shop_id)
		where = "shop_id = #{shop_id}" if shop_id > 0
		@tasks_grid = initialize_grid(ShopItem,
		:include => [:shop],
		:conditions => where,
	     :custom_order => {
	    })
	end

end

app/controllers/user_center/keyword_records_controller.rb
class UserCenter::KeywordRecordsController < ApplicationController

	before_filter :authenticate_user!
 	layout 'smart_admin'


	def index

		# @records = []
		# ShopKeywordRecord.includes(:shop,:shop_item,:shop_keyword).select('t3.user_id').where("user_id =  #{current_user.id}").each do |r|
		# 	@records << {
		# 		'title' => r.shop.title,
		# 		'shop_id'=>r.shop_id,
		# 		'item_title' => r.shop_item.title,
		# 		'item_id' => r.item_id,
		# 		'rank' => r.rank,
		# 		'keyword' => r.shop_keyword.keyword
		# 	}

		# end	

		last_time = Time.now.beginning_of_day
		if ShopKeywordRecord.where(['created_at > ?',last_time]).size == 0
			last_time = last_time - 1.day
		end
		@records = initialize_grid(                                                                #where("user_id = 1 ")
		  ShopKeywordRecord.includes(:shop,:shop_item,:shop_keyword).select('shop_keywords.user_id').where("user_id = #{current_user.id}").where(['

		  	shop_keyword_records.created_at >=?',last_time]),

	     :custom_order => {
	    })
	end

		

	def trend
		record = ShopKeywordRecord.find(params[:id])


		start_time = Time.now.end_of_day-30.days
		end_time = Time.now.end_of_day


		records = ShopKeywordRecord.select(' date_format(created_at,"%y-%m-%d") as time,avg(rank) as rank').where(
			['shop_id = ? and item_id = ? and shop_keyword_id = ? and created_at between ? and ?',record.shop_id,record.item_id,record.shop_keyword_id,start_time,end_time]).group('time').order('time asc')



		res = []
		start_time_stamp = start_time.beginning_of_day.to_i
		end_time_stamp = end_time.beginning_of_day.to_i
		current_time_stamp = start_time_stamp
		one_day_sec = 1.day
		
		index = 0
		31.times do |i|
			if Time.at(current_time_stamp).strftime('%y-%m-%d') == records[index].time
				res << records[index].rank
				index += 1
				index = 0 if index >= records.size
			else
				res << 0
			end

			current_time_stamp += one_day_sec
		end
		res

		respond_to do |format|
		  format.json { render :json => res }
		end

	end
end

app/controllers/user_center/keywords_controller.rb
#encoding:utf-8
class UserCenter::KeywordsController < ApplicationController
	before_filter :authenticate_user!
	layout 'smart_admin'

	def index
		@shops_map ={}
	 	Shop.watched(current_user.id).each do |r|
	 		@shops_map[r.id] = r.title
		end
		@keywords = current_user.keywords
	end


	def new
	  	@keyword = ShopKeyword.new
	  	# respond_to do |format|
	   #    format.html { render :layout => false }
	   #  end

	end



	def create

	 	data = params[:shop_keyword]
	 	data["shops"] = data["shops"].join(",").chomp(',')
	 	data["user_id"] = current_user.id

	 	@keyword = ShopKeyword.new(data)
		if @keyword.save
			flash[:notice] = '关键字创建成功.'
			redirect_to :action => :index
		else

			render :action => :new
		end
	end


	def destroy
		  @keyword = ShopKeyword.find(params[:id])
		  @keyword.destroy
		  flash[:notice] = '删除成功.'
		  redirect_to :action => :index

	end
end

app/controllers/user_center/shops_controller.rb
#encoding:utf-8
class UserCenter::ShopsController < InheritedResources::Base
  include StaticsHelper
  include UserCenterHelper

  
  before_filter :authenticate_user!

  layout 'smart_admin'

  def index


  end


  def new
  	@shop = Shop.new
  end



  def create
    create! do |success, failure|
      
      success.html { 
        current_user.follow(@shop)
        redirect_to user_center_shops_path,:notice=>'创建成功'
      }
    end
  end



  def subscribe

  		shop_id = params['shop_id'].to_i

  		#@TODO replace with current_user
  		current_user.follow( Shop.find(shop_id)) 

  		render text: shop_id.to_s
  end


  def unsubscribe

  		shop_id = params['shop_id'].to_i

  		#@TODO replace with current_user

  		current_user.stop_following( Shop.find(shop_id)) 

  		render text: shop_id.to_s


  end



  def compare

    @offset = params['offset'].to_i
    @offset ||= 0
    shops = params['id'].split(',')
    shops.collect! &:to_i



    @res = []

    shops.each do |s|
      shop = Shop.find(s)
      row = {'title' => shop.title,'id'=>shop.id}
      row['sales'] = get_sales_history(shop.id,@offset)

      
      @res << row
    end

  end


  def show
    #time = Time.now.beginning_of_day
    offset = params['offset'].to_i

    offset ||= 0
    @shop = Shop.find(params['id'])

    @today = calc_sales_count_and_money(@shop.today_sales(offset))

    yesterday = calc_sales_count_and_money(@shop.today_sales(offset + 1 ))

    lastweekday = calc_sales_count_and_money(@shop.today_sales(offset + 7 ))



    today_changes_sales = today_changes(@shop.id,offset)

    @yes_compare = get_compare_rate(@today,yesterday)

    @lastweekday_compare = get_compare_rate(@today,lastweekday)

    sales_history = get_sales_money_history(@shop.id,offset)
    count_history = get_sales_count_history(@shop.id,offset)

    sales_total = sales_history.inject(0) {|sum,i| sum + i} 
    count_total= count_history.inject(0) {|sum,i| sum + i} 


    @locals = { :today => @today,:lastweekday_compare => @lastweekday_compare, :sales_history=>sales_history,:count_history => count_history,
    :yes_compare => @yes_compare ,:shop => @shop ,:offset=>offset,:today_changes_sales => today_changes_sales,
    :sales_total =>sales_total,:count_total=>count_total

    }

    #hack ugly?
    respond_to do |format|
      format.html
      format.js {
         render :partial => 'show_data',:locals => @locals,:layout=>false ,:mime_type => Mime::Type.lookup('text/html')
      }
    end

    #5 top items
  end





end

app/controllers/user_center/test_controller.rb
class UserCenter::TestController < ApplicationController
  def index
  end
end

app/controllers/user_center_controller.rb
class UserCenterController < ApplicationController
	
  helper StaticsHelper
  before_filter :authenticate_user!
  layout 'smart_admin'


  def index
  	@offset = params['offset'].to_i
  	@shops = current_user.following_by_type('Shop')

  end


end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/user_center/items_helper.rb
module UserCenter::ItemsHelper
end

app/helpers/user_center/keyword_records_helper.rb
module UserCenter::KeywordRecordsHelper
end

app/helpers/user_center/keywords_helper.rb
module UserCenter::KeywordsHelper

	def shopids_to_titles(ids,maps)
		ids = ids.split(',')

		res = ''
		ids.each do |id|
			id = id.to_i
			res = res + maps[id] + '&nbsp;' if maps[id]
		end
		res
	end



end

app/helpers/user_center_helper.rb
#encoding:utf-8
module UserCenterHelper

	def link_with_cur(path,title)
		cur = 'cur' if request.path == path
		"<li><a href='#{path}' class='#{cur}'><i class='icon-chevron-right'></i> #{title} </a></li>"
	end



	def today_change_count(shop,offset =0)

			 ShopItemVersion.today_changes(shop,offset).size +  
			 ShopItemContentVersion.today_changes(shop,offset).size
	end
	

	def my_img_tag(thumb,css_class)
		"<img  class='#{css_class}' src='#{thumb}'>"
	end

	def today_changes(shop,offset=0)


		res = []

  		today_changes = ShopItemVersion.today_changes(shop,offset)
		
		today_changes_cache = {}
  		today_changes.each do |r|
  			today_changes_cache["#{r.shop_item_id}_#{r.version}"] = r
  		end

		today_changes.each do |r|
			item = today_changes_cache["#{r.shop_item_id}_#{r.version}"]

			if item.version != 1
				last = item
				prev = today_changes_cache["#{r.shop_item_id}_#{r.version-1}"]

				if prev.nil?
					prev = ShopItemVersion.includes(:shop_item).where(:shop_item_id => r.shop_item_id,:version=>r.version-1).limit(1).first
				end


				change = "［商品］：<a href='/shop_items/#{item.shop_item.id}' >#{last.title}</a> "

				change += " 价格变化 #{prev.price} => #{last.price}" if last.price != prev.price

				change += " 标题变化 #{prev.title} => #{last.title}" if last.title != prev.title
				
				change += " 状态变化 #{ShopItem.status_text prev.status} => #{ShopItem.status_text last.status}" if last.status != prev.status

				change += " 主图变化 #{my_img_tag prev.thumb,'small'} => #{my_img_tag last.thumb,'small'}" if last.thumb != prev.thumb

			else
				change = "［新品］:<a href='/shop_items/#{item.shop_item.id}' >#{item.title}</a> 新上架"

			end

			res << change

		end 




	 	ShopItemContentVersion.today_changes(shop,offset).each do |r|
	 		item = ShopItemContent.find(r.shop_item_content_id)
	 		if item.versions.count != 1
		 		last = item.versions.last
				prev = last.previous


		 		change = "［内容］:<a href='/shop_items/#{item.shop_item.id}' >#{item.shop_item.title}</a> 内容变化 "

				change +=  " <a href='/shop_items/#{item.shop_item.id}/content/#{last.version}/#{prev.version}' > 对比 </a>"

				#{content_compare_path(:id=>item.shop_item.id,:fversion=>last.version,:sversion=>prev.version)}

			else
				change = "［内容］:<a href='/shop_items/#{item.shop_item.id}' >#{item.shop_item.title}</a> 内容创建"

			end

			res << change

	 	end


	 	res

	end


	def today_sales(shop,offset=0)
		res = {}
		sales = shop.today_sales(offset)
		sales.each do |s|
			if !res[s.shop_item.id]
				row = {}
				row['item'] = link_to s.shop_item.title, "/shop_items/#{s.shop_item.id}"
				row['img'] = link_to image_tag(s.shop_item.thumb),"/shop_items/#{s.shop_item.id}"
				row['count'] = s.item_num.to_i
				row['money'] = s.item_num.to_i * s.item_price.to_f
				res[s.shop_item.id] = row
			else
				res[s.shop_item.id]['count'] += s.item_num.to_i
				res[s.shop_item.id]['money'] += s.item_num.to_i* s.item_price.to_f
			end
		end
		res = res.to_a.sort do |a,b|
			b[1]['money'] <=>  a[1]['money']
		end
		res
	end


	def get_preview(id,time)
		"/preview/#{id}/#{time.strftime('%Y-%m-%d')}.jpg"
	end

	def get_preview_small(id,time)
		"/preview/#{id}/#{time.strftime('%Y-%m-%d')}-small.jpg"
	end


	def get_change_icon(status)
		if status == 1
			'<img src="/assets/zeng.gif">'.html_safe
		else
			'<img src="/assets/jian.gif">'.html_safe
		end

	end

	def get_sales_history(id,offset,search_way = :by_shop)
		start_time = Time.now.end_of_day-30*24*3600 -offset*24*3600 
		end_time = Time.now.end_of_day-offset*24*3600
		#ShopItem.includes(:shop_item).
		#ItemSale.joins(:shop_item).select('date_format(buy_time,"%y-%m-%d") as time ,sum(item_price * item_num) as total').where(['shop_id = 1 and buy_time between ? and ?',Time.now-3*24*3600 , Time.now]).group('time')
		
		conditions = nil
		if search_way === :by_shop
			conditions = ['shop_id = ? and buy_time between ? and ?',id,start_time,end_time]
		else #by_item
			conditions = ['shop_items.id = ? and buy_time between ? and ?',id,start_time,end_time]
		end


		sales = ItemSale.joins(:shop_item).select(' date_format(buy_time,"%y-%m-%d") as time,count(DISTINCT buy_time,user_name) as item_count, sum(item_price * item_num) as total').where(conditions).group('time').order('time asc')
		

		res = []
		start_time_stamp = start_time.beginning_of_day.to_i
		end_time_stamp = end_time.beginning_of_day.to_i
		current_time_stamp = start_time_stamp
		one_day_sec = 3600*24
		sales_index = 0

		if sales[0]
			31.times do |i|
				if Time.at(current_time_stamp).strftime('%y-%m-%d') == sales[sales_index].time
					res << [ sales[sales_index].item_count.to_i,sales[sales_index].total.round(2)]
					sales_index += 1
					sales_index = 0 if sales_index >= sales.size
				else
					res << [0,0]
				end

				current_time_stamp += one_day_sec
			end
		else
			31.times do |i|
				res << [0,0]
			end
		end
		res
	end


	def get_sales_money_history(id,offset,search_way = :by_shop)
		res = get_sales_history(id,offset,search_way)
		res.collect &:second
	end


	def get_sales_count_history(id,offset,search_way = :by_shop)
		res = get_sales_history(id,offset,search_way)
		res.collect &:first
	end
	#sales_history = get_sales_histroy(@shop,offset)

end

app/views/user_center/shops/index.html.erb
<% if notice %>
<div class="alert alert-success">
	<strong><%= notice %></strong>
</div>
<% end %>

<div class="span3 offset3">
		<i class="icon-plus"></i>
		<%= link_to '新增', new_user_center_shop_path %>
</div>

<div class="clearfix"></div>



<section id="unwatched_list">
	<div >
		<h3>未订阅</h3>
		<div class="row">

			<% Shop.unwatched(current_user.id).each do |shop| %>
				<li class="col-xs-12 col-sm-6 col-md-3 " shop-id='<%=shop.id%>'> 
					标题: <%= link_to shop.title,user_center_shop_path(shop) %> <br>
					地址： <%= link_to shop.url.first(30),shop.url  %> <br>
					产品数: <%=shop.shop_items.count %> <br>

					<a class="btn btn-info scribe" > 订阅 </a>

				</li>
			<% end %>


		</div>
		

	</div>
</section>

<hr>

<section id="watched_list">
	<div >
		<h3>已订阅</h3>
		<div class="row">

			<% Shop.watched(current_user.id).each do |shop| %>
				<li class="col-xs-12 col-sm-6 col-md-3 " shop-id='<%=shop.id%>'> 
					标题: <%= link_to shop.title,user_center_shop_path(shop) %><br>
					地址： <%= link_to shop.url.first(30),shop.url  %><br>
					产品数: <%=shop.shop_items.count %> <br>

					<a class="btn btn-info scribe" > 取消订阅 </a>
				</li>
			<% end %>


		</div>
		

	</div>
</section>

<%= content_for :script do %>
<script type="text/javascript">
	$(function(){

		var unwatched_func = function(){

			var li = $(this).closest('li');
			var ul = $(li).parent();

			var another_ul = $('section#watched_list div.row');
			//animate
			$(li).hide('normal',function(){


				//ajax
				$.ajax({
					'type':'POST',
					'url':'<%=subscribe_user_center_shops_path%>',
					'data':{'shop_id':$(li).attr('shop-id')},
					'success':function(){}
				})
				//change li
				$(li).find('a.btn').html('取消订阅');
				$(li).find('a.btn').unbind();
				$(li).find('a.btn').click(watched_func);

				$(another_ul).append(li);
				$(li).show('normal');
			});


		};

		var watched_func = function(){

			var li = $(this).closest('li');
			var ul = $(li).parent();

			var another_ul = $('section#unwatched_list div.row');
			//animate
			$(li).hide('normal',function(){
				//ajax
				$.ajax({
					'type':'POST',
					'url':'<%=unsubscribe_user_center_shops_path%>',
					'data':{'shop_id':$(li).attr('shop-id')},
					'success':function(){}
				})
				//change li
				$(li).find('a.btn').html('订阅');
				$(li).find('a.btn').unbind();
				$(li).find('a.btn').click(unwatched_func);


				$(another_ul).append(li);
				$(li).show('normal');
			});


		};


		$('section#unwatched_list .row li a.scribe').click(unwatched_func);


		$('section#watched_list .row li a.scribe').click(watched_func);


	});

	
</script>

<% end %>

app/views/user_center/shops/new.html.erb
<section id="widget-grid" class="">
	
	<!-- row -->
	<div class="row">
	
		<!-- NEW WIDGET START -->
		<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	

			
		<div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false">
			
			<header>
				<span class="widget-icon"> <i class="fa fa-eye"></i> </span>
				<h2>新增店铺</h2>

			</header>

			<!-- widget div-->
			<div>

				<!-- widget edit box -->
				<div class="jarviswidget-editbox">
					<!-- This area used as dropdown edit box -->

				</div>
				<!-- end widget edit box -->

				<!-- widget content -->
				<div class="widget-body">

						

<%= simple_form_for @shop, :url => user_center_shops_path,:methos=>'create' do |f| %>

	 <% if notification = f.error_notification %>
	    <div class="alert alert-error fade in">
	      <a class="close" data-dismiss="alert" href="#">&times;</a>
	      <%= notification %>
	    </div>
	  <% end %>


	  <%= f.input :title,:label=>'店铺名称',:input_html => { :class => "span6" }, :hint => "请用汉语标示 示例:三六五食品专营店" %>
	  <%= f.input :url,:label=>'店铺链接', :input_html => { :class => "span6" }, :hint => "请输入首页地址 示例: http://slwsp.tmall.com/" %>


	  <div class="text-center">
	  	<%= f.button :submit ,:class=>'btn btn-primary'%>
	  </div>


<% end %>


	</div>
			</div>
		</div>


		</article>
</div>
</section>

<%= content_for :script do %>
<script type="text/javascript">
	
	$(function(){

		$('#shop_url').blur(function(){

			//if( /^http:\/\/\w*\.(tmall|taobao)\.com\//i.test($(this).val()))
			if( /^http:\/\/\w*\.(tmall)\.com\//i.test($(this).val()))
			{
				modify_val = $(this).val().substr(0,  $(this).val().indexOf("com/") + 4 );

				$(this).val(modify_val);
			}

		})

	})

</script>
<% end %>

app/views/user_center/shops/show.html.erb
	

	<div id="date_box" class="DI_SU_time span12"> 
		<div class="date_d_date_box">   
		<div class="date_d_quickDate">     <a class="date_d_dateActive" href="javascript:void(0)">&lt;&lt;&nbsp;前一天</a>     <input id="J_quick_timer" class="date_d_dateValue" readonly="readonly"  disabled="disabled">     <a class="date_d_dateSpec date_d_dateDeactive" href="javascript:void(0)">后一天&nbsp;&gt;&gt;</a>   
		</div>   
		<div class="date_d_timerBox">  <p>选择时间</p>   
			<div class="input-append date date_d_timeInput ">
			  <input type="text" ><span class="add-on"><i class="icon-th"></i></span>

			</div>

			<div class="date_d_timeSearch" >
				
			  	<a class="btn" id="search"> 查询 </a>

			</div>

			<!-- <input id="st_time_input" readonly="readonly" class="date_d_timeInput" type="text" autocomplete="off" value="" daterange="2014-02-14..2014-02-14"> -->
		 </div> 


		</div>
	</div>


	<div class="clearfix"> </div>
	<div class="sections">
		<%= render :partial => "/user_center/shops/show_data",:locals => @locals%>  

	</div>


<%= content_for :script do %>
<script type="text/javascript">
	$(function(){
		

		function datapick_init()
		{

			var datapicker = $('.input-append.date');
			var today = new Date(); 
			today = new Date(today.getFullYear(),(today.getMonth()),today.getDate());
			var current = today;
			var fclick = $('.date_d_quickDate a:first');
			var lclick = $('.date_d_quickDate a:last');


			function fmtdate(d)
			{
				return d.getFullYear()+"-"+(d.getMonth()+1)+"-"+d.getDate();
			}

			function setDate(date)
			{

				current = date;
				$('#J_quick_timer').val(fmtdate(date));

				if(current.valueOf() === today.valueOf())
				{

					lclick.toggleClass('date_d_dateActive date_d_dateDeactive');

				}
				else if(lclick.hasClass('date_d_dateDeactive'))
				{
					lclick.toggleClass('date_d_dateActive date_d_dateDeactive');
				}
				 $('.sections').html('');


				 var timeDiff = Math.abs(today.getTime() - current.getTime());
				 var diffDays = Math.ceil(timeDiff / (1000 * 3600 * 24));
				 $.ajax({
		            url: "<%= user_center_shop_path(@shop,:format => 'js')%>",
		            type: "GET",
		            data: {
		            	'offset':  diffDays ,
		            	'_rdm':Math.random()
		            },
		            dataType:"text",
		            success: function(data) {
		            	//alert(data);
		               $('.sections').html(data);
		            },
					  error: function(e){
					   // alert(e);
					  }
		          });




			}

			datapicker.datepicker({
				language: 'zh-CN',
				endDate: today,
			});

		

			
			$('#J_quick_timer').val(fmtdate(current))

			$('#search').click(function(){

				
				var date = $('.input-append.date').datepicker('getDate');
				setDate(date);
			})



			//previous day
			fclick.click(function(){
				setDate(new Date(current.valueOf()-24*60*60*1000));
			})

			lclick.click(function(){
				t_time = new Date(current.valueOf()+24*60*60*1000);
				if(t_time.valueOf()<= today.valueOf())
				{
					setDate(t_time);

				}
			});

		};

		datapick_init();

	})


</script>
<% end %>